-- ============================================================
-- 06 | News-Tabelle (Ankuendigungen an alle Nutzer)
-- Einmal im Supabase SQL Editor ausfuehren.
-- Danach postest du Meldungen bequem ueber den Table Editor:
-- Table Editor -> news -> Insert row (titel + text reichen).
-- RLS bleibt AUS (wie bei leaderboard) - kein zusaetzlicher
-- Schritt noetig.
-- ============================================================

create table if not exists news (
  id        bigint generated by default as identity primary key,
  titel     text not null,
  text      text not null,
  erstellt  timestamptz not null default now()
);

-- Erste Meldung als Beispiel/Start (kannst du spaeter loeschen):
insert into news (titel, text) values
  ('Neu: Profile!',
   'Jetzt koennen sich mehrere Spieler ein Geraet teilen - jeder mit eigenem Namen und eigenem Fortschritt. Einfach beim Start auf deinen Namen tippen.');
